server:
  port: 8301
spring:
  application:
    name: ribbon-service
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
service-url:
  user-service: http://user-service
# 挂在服务名称下面，如下是对ribbon-service调用user-service时的单独配置
#    ribbon:
#      ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#      ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#      OkToRetryOnAllOperations: true #对超时请求启用重试机制
#      MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#      MaxAutoRetries: 1 # 切换实例后重试最大次数
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法